<?php

namespace App\Filament\Admin\Resources\AssetEmployeeResource\Pages;

use App\Filament\Admin\Resources\AssetEmployeeResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditAssetEmployee extends EditRecord
{
    protected static string $resource = AssetEmployeeResource::class;
    public static function canAccess(array $parameters = []): bool
    {
        return $parameters['record']->status==="Pending"; // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }
}
