<?php

namespace App\Filament\Admin\Resources\GrnResource\Pages;

use App\Filament\Admin\Resources\GrnResource;
use Filament\Actions;
use Filament\Infolists\Components\Section;
use Filament\Infolists\Components\TextEntry;
use Filament\Infolists\Infolist;
use Filament\Resources\Pages\ViewRecord;

class ViewGrn extends ViewRecord
{
    protected static string $resource = GrnResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\EditAction::make()->hidden(function ($record){
                return $record->items()->where('receive_status','!=','Approved')->count();
            }),
        ];
    }
    public function infolist(Infolist $infolist): Infolist
    {
        return $infolist->schema([
           Section::make([
               TextEntry::make('purchaseOrder.purchase_orders_number')->label('PO No')->prefix('ATGT/UNC/'),
               TextEntry::make('number')->label('GRN No')->prefix('ATGT/UNC/'),
               TextEntry::make('manager.fullName'),
               TextEntry::make('received_date')->label('Received Date')->dateTime(),
//               TextEntry::make('items_sum_total'),
           ])->columns()
        ]); // TODO: Change the autogenerated stub
    }
}
