<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::table('roles')->insert([
            ['id' => 1, 'name' => 'Admin', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now() ,'company_id' =>  1,],
            ['id' => 2, 'name' => 'CEO', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now() ,'company_id' =>  1,],
            ['id' => 3, 'name' => 'Head', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now() ,'company_id' =>  1,],
            ['id' => 4, 'name' => 'Logestic', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now() ,'company_id' =>  1,],
            ['id' => 5, 'name' => 'User', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now() ,'company_id' =>  1,],
            ['id' => 6, 'name' => 'Security', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now() ,'company_id' =>  1,],
            
        ]);
        // $premissions = [

        //     ['name' => 'view_account', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_account', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_account', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_account', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_account', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_account', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_account', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_account', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_account', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_account', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_account', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_account', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_account::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_account::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_account::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_account::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_account::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_account::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_account::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_account::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_account::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_account::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_account::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_account::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_bank::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_bank::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_bank::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_bank::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_bank::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_bank::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_bank::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_bank::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_bank::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_bank::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_bank::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_bank::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_benefit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_benefit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_benefit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_benefit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_benefit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_benefit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_benefit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_benefit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_benefit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_benefit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_benefit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_benefit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_contract', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_contract', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_contract', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_contract', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_contract', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_contract', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_contract', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_contract', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_contract', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_contract', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_contract', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_contract', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_customer', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_customer', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_customer', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_customer', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_customer', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_customer', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_customer', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_customer', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_customer', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_customer', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_customer', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_customer', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_department', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_department', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_department', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_department', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_department', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_department', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_department', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_department', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_department', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_department', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_department', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_department', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_duty', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_duty', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_duty', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_duty', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_duty', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_duty', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_duty', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_duty', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_duty', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_duty', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_duty', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_duty', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_employee', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_employee', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_employee', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_employee', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_employee', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_employee', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_employee', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_employee', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_employee', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_employee', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_employee', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_employee', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_expense', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_expense', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_expense', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_expense', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_expense', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_expense', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_expense', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_expense', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_expense', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_expense', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_expense', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_expense', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_financial::period', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_financial::period', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_financial::period', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_financial::period', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_financial::period', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_financial::period', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_financial::period', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_financial::period', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_financial::period', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_financial::period', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_financial::period', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_financial::period', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_holiday', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_holiday', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_holiday', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_holiday', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_holiday', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_holiday', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_holiday', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_holiday', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_holiday', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_holiday', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_holiday', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_holiday', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_income', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_income', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_income', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_income', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_income', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_income', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_income', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_income', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_income', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_income', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_income', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_income', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_inventory', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_inventory', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_inventory', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_inventory', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_inventory', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_inventory', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_inventory', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_inventory', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_inventory', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_inventory', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_inventory', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_inventory', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_invoice', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_invoice', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_invoice', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_invoice', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_invoice', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_invoice', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_invoice', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_invoice', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_invoice', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_invoice', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_invoice', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_invoice', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_loan', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_loan', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_loan', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_loan', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_loan', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_loan', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_loan', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_loan', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_loan', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_loan', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_loan', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_loan', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_payroll', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_payroll', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_payroll', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_payroll', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_payroll', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_payroll', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_payroll', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_payroll', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_payroll', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_payroll', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_payroll', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_payroll', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_position', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_position', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_position', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_position', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_position', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_position', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_position', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_position', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_position', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_position', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_position', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_position', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_product', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_product', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_product', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_product', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_product', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_product', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_product', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_product', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_product', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_product', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_product', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_product', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_product::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_product::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_product::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_product::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_product::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_product::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_product::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_product::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_product::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_product::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_product::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_product::category', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_role', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_role', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_role', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_role', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_role', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_role', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_structure', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_structure', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_structure', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_structure', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_structure', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_structure', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_structure', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_structure', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_structure', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_structure', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_structure', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_structure', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_trans::action', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_trans::action', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_trans::action', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_trans::action', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_trans::action', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_trans::action', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_trans::action', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_trans::action', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_trans::action', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_trans::action', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_trans::action', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_trans::action', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_type::leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_type::leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_type::leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_type::leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_type::leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_type::leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_type::leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_type::leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_type::leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_type::leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_type::leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_type::leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_unit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_unit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_unit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_unit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_unit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_unit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_unit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_unit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_unit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_unit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_unit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_unit', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_vendor', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_vendor', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_vendor', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_vendor', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_vendor', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_vendor', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_vendor', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_vendor', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_vendor', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_vendor', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_vendor', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_vendor', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_vendor::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_vendor::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_vendor::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_vendor::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_vendor::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_vendor::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_vendor::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_vendor::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_vendor::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_vendor::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_vendor::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_vendor::type', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_warehouse', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'view_any_warehouse', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create_warehouse', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'update_warehouse', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_warehouse', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'restore_any_warehouse', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'replicate_warehouse', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'reorder_warehouse', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_warehouse', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'delete_any_warehouse', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_warehouse', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'force_delete_any_warehouse', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'page_AccountSettings', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'page_Employee', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'page_HrSettings', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'page_Leave', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'page_Loan', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'create-posts', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],
        //     ['name' => 'edit-posts', 'guard_name' => 'web', 'created_at' => now(), 'updated_at' => now()],

        // ];
        // DB::table('permissions')->insert([
        //     ...$premissions
        // ]);

        // DB::table('model_has_permissions')->insert(
        //     collect(range(1, count($premissions)))->map(function ($permissionId) {
        //         return [
        //             'permission_id' => $permissionId,
        //             'model_type' => 'App\\Models\\User',
        //             'model_id' => 1,
        //             'company_id' =>  1,
        //         ];
        //     })->toArray()
        // );

        DB::table('model_has_roles')->insert([
            ['role_id' => 1, 'model_type' => 'App\\Models\\User', 'model_id' => 1, 'company_id' => 1],
            ['role_id' => 2, 'model_type' => 'App\\Models\\User', 'model_id' => 1, 'company_id' => 1],
            ['role_id' => 3, 'model_type' => 'App\\Models\\User', 'model_id' => 2, 'company_id' => 1],
            ['role_id' => 4, 'model_type' => 'App\\Models\\User', 'model_id' => 3, 'company_id' => 1],
        ]);
      
    }

    public function down()
    {
        Schema::dropIfExists('model_has_permissions');
        Schema::dropIfExists('model_has_roles');
        Schema::dropIfExists('permissions');
        Schema::dropIfExists('roles');
    }
};
