<?php

namespace App\Filament\Admin\Pages;

use Filament\Pages\Page;
use Illuminate\Contracts\Support\Htmlable;

class Chat extends Page
{
    protected static ?string $navigationIcon = 'heroicon-o-chat-bubble-oval-left';
    public function getTitle(): string|Htmlable
    {
        return '';
    }
    public static function getNavigationBadge(): ?string
    {
        return   auth()->user()->getUnreadCount();
    }
    public static function getNavigationBadgeColor(): string|array|null
    {
        return 'danger'; // TODO: Change the autogenerated stub
    }

    protected static string $view = 'filament.admin.pages.chat';
}
