<?php

namespace App\Filament\Admin\Resources\BankResource\Pages;

use App\Filament\Admin\Resources\BankResource;
use App\Filament\Admin\Resources\CashResource;
use App\Models\Account;
use App\Models\Bank;
use App\Models\Currency;
use Filament\Actions;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\Section;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Form;
use Filament\Forms\Get;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Validation\Rules\Unique;

class EditCash extends EditRecord
{
    protected static string $resource = BankResource::class;
    public function form(Form $form): Form
    {
        return $form->schema([
            Section::make([
                TextInput::make('name')->required()->maxLength(254),
                TextInput::make('account_code')->default(function () {
                    if (Bank::query()->where('company_id', getCompany()->id)->where('type', 1)->latest()->first()) {
                        return generateNextCode(Bank::query()->where('company_id', getCompany()->id)->latest()->first()->account_code);
                    } else {
                        return "001";
                    }
                })->prefix(fn(Get $get) => Account::query()->firstWhere('id', $this->record?->account?->parent_id)?->code)->required()->maxLength(255),
                Select::make('currency_id')->label('Currency')->default(getCompany()->currencies->where('is_company_currency',1)->first()?->id)->required()->options(getCompany()->currencies->pluck('name','id'))->searchable()->createOptionForm([
                    Section::make([
                        TextInput::make('name')->required()->maxLength(255),
                        TextInput::make('symbol')->required()->maxLength(255),
                        TextInput::make('exchange_rate')->required()->numeric(),
                    ])->columns(3)
                ])->createOptionUsing(function ($data){
                    $data['company_id']=getCompany()->id;
                    Notification::make('success')->title('success')->success()->send();
                    return  Currency::query()->create($data)->getKey();
                }),
                ])->columns(3),
            Textarea::make('description')->columnSpanFull(),
            Hidden::make('type')->default(1),
        ]);
    }
    protected function getRedirectUrl(): string
    {
        return CashResource::getUrl('index'); // TODO: Change the autogenerated stub
    }
}
